import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import WalletContextProvider from "@/context/wallet";
import { headers } from "next/headers";
import AppProvider from "@/context";

const workSans = Work_Sans({
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900"
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersData = await headers();
  const cookies = headersData.get("cookie");

  return (
    <html lang="en">
      <body
        className={`${workSans.className} antialiased`}
      >
        <WalletContextProvider cookies={cookies}>
          <AppProvider>{children}</AppProvider>
        </WalletContextProvider>
      </body>
    </html>
  );
}
