import './globals.css';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import WalletContextProvider from '@/context/wallet';
import { headers } from 'next/headers';
import AppProvider from '@/context';
import { ThemeProvider } from 'next-themes';
import StoreProvider from '@/components/providers/store-provider';

const workSans = Work_Sans({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Datasets Marketplace',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const headersData = await headers();
	const cookies = headersData.get('cookie');

	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${workSans.className} antialiased overscroll-x-none`}>
				<ThemeProvider attribute={'class'} defaultTheme={'system'} enableSystem>
					<WalletContextProvider cookies={cookies}>
						<StoreProvider>
							<AppProvider>{children}</AppProvider>
						</StoreProvider>
					</WalletContextProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
